apiVersion: v1
kind: Pod
metadata:
  name: kuard-tls
spec:
  containers:
    - name: kuard-tls
      image: gcr.io/kuar-demo/kuard-amd64:blue
      imagePullPolicy: Always
      resources:
        limits:
          cpu: "100m"
          memory: "64Mi"
      ports:
        - containerPort: 8443
          name: http
          protocol: TCP
      volumeMounts:
        - name: tls-certs
          mountPath: /tls
          readOnly: true
  # to pull an image from a private registry
  # imagePullSecrets:
  #   - name: my-image-pull-secrets
  volumes:
    - name: tls-certs
      secret:
        secretName: kuard-tls