apiVersion: v1
kind: Pod
metadata:
  name: kuard
  labels:
    name: "kuard"
    book: "oreilly.com_k8s-up-and-running"
spec:
  volumes:
    - name: "kuard-data"
      hostPath:
          path: "/var/lib/kuard"  # mount arbitraty location on a host
    # - name: "kuard-nfs-data"
    #   nfs:
    #     server: my.nfs.server.local
    #     path: "/exports"
  containers:
  - name: kuard
    image: gcr.io/kuar-demo/kuard-amd64:blue
    volumeMounts:
      - mountPath: "/data"
        name: "kuard-data"
    livenessProbe:
        httpGet:
          path: /healthy
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
    resources:
      requests:
        cpu: "100m"  # millicores
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
    ports:
      - containerPort: 8080
        name: http
        protocol: TCP
